/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ginryan_lameslab_mp3encoder_MP3Encoder */

#ifndef _Included_org_ginryan_lameslab_mp3encoder_MP3Encoder
#define _Included_org_ginryan_lameslab_mp3encoder_MP3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ginryan_lameslab_mp3encoder_MP3Encoder
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_ginryan_lameslab_mp3encoder_MP3Encoder_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_ginryan_lameslab_mp3encoder_MP3Encoder
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_org_ginryan_lameslab_mp3encoder_MP3Encoder_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     org_ginryan_lameslab_mp3encoder_MP3Encoder
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_ginryan_lameslab_mp3encoder_MP3Encoder_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_ginryan_lameslab_mp3encoder_MP3Encoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ginryan_lameslab_mp3encoder_MP3Encoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
